### ISSUE TITLE
Getting an unknown host acception, how to resolve this?

### ISSUE THREAD

**Issue by GajenderI** [Mapepire-IBMi/mapepire-server#64]
Getting an unknown host acceprtion, how to resolve this?

java.net.UnknownHostException: hiddenthename.COM: hiddenthename.COM: Hostname and service name not provided or found
at java.net.InetAddress.getLocalHost(InetAddress.java:1685)
at com.github.ibm.mapepire.certstuff.SelfSignedCertGenerator.generate(SelfSignedCertGenerator.java:24)
at com.github.ibm.mapepire.certstuff.ServerCertGetter.get(ServerCertGetter.java:102)
at com.github.ibm.mapepire.MapepireServer.main(MapepireServer.java:74)
Caused by: java.net.UnknownHostException: hiddenthename.COM: Hostname and service name not provided or found
at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:1048)
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1462)
at java.net.InetAddress.getLocalHost(InetAddress.java:1680)
... 3 more

**Comment by SanjulaGanepola** [comment]
Hello @GajenderI. Thank you for posting this issue. This problem is likely because it cannot resolve your host name. Can you use the `CFGTCP` command with option 10 and add the associated host name and IP address? Then try running the mapepire server again.

![image](https://github.com/user-attachments/assets/48702d74-871f-4623-8d66-b435eadd3df3)

**Comment by ThePrez** [comment]
Hi, @GajenderI , can you also confirm if running the `hostname` command from a shell (SSH, qp2term, qsh) returns a valid response?
