### ISSUE TITLE
Unable to Start Mapepire on V7R5 Using Service Commander or Manual Shell Invocation

### ISSUE THREAD

**Issue by i-enthusiast** [Mapepire-IBMi/mapepire-server#67]
Environment: V7R5 with latest PTFs.

I followed the steps here and successfully installed Mapepire and Service Commander.
https://mapepire-ibmi.github.io/guides/sysadmin/

I then attempted to start Mapepire in bash with the following command:
`sc start mapepire`

I receive the following error:
`ERROR: Timed out waiting for service 'Mapepire Server' to start`

Manual Invocation with the following command does not start the service as well:
`nohup /QOpenSys/pkgs/bin/mapepire &`

I also documented this issue over on the Service Commander Github:
https://github.com/ThePrez/ServiceCommander-IBMi/issues/229#issue-2514843197

**Comment by i-enthusiast** [comment]
When attempting to start it via invoking from `/QOpenSys/pkgs/bin/mapepire`, I receive the following output:
`Starting daemon...2024-09-10 10:44:19.379:INFO::main: Logging initialized @326ms to org.eclipse.jetty.util.log.StdErrLog
bye`

The service doesn't appear to start:
- `sc list group:all` shows the service, but `sc check group:all` shows a status of NOT RUNNING
- `scopenports` doesn't list the port as active
- An Nmap scan against the IBM i LPAR doesn't show the port 8076 as open
- From IBM i CL, `===> NETSTAT`, Option 3 does not show any service listening on 8076 either.

**Additional Info**
```
bash-5.2$ sc info mapepire


---------------------------------------------------------------------
mapepire (Mapepire Server)


Defined in: /QOpenSys/pkgs/lib/mapepire/mapepire.yaml

Working Directory: .

Startup Command: ../../bin/mapepire
Startup Wait Time (s): 60

Shutdown Wait Time (s): 45

Check-alive conditions: JOBNAME:MAPEPIRE, PORT:8076
Batch Mode: <submitted to batch>
    Batch Job Name: MAPEPIRE
    SBMJOB options: JOBQ(QUSRNOMAX)

Inherits environment variables?: true
Custom environment variables:
    PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
---------------------------------------------------------------------
```

**Comment by i-enthusiast** [comment]
With the help of @ThePrez, I was able to identify and correct the issue.

As suggested by @ThePrez, the following command was executed to view startup logs:
```
QIBM_JAVA_STDIO_CONVERT=N QIBM_PASE_DESCRIPTOR_STDIO=B QIBM_USE_DESCRIPTOR_STDIO=Y QIBM_MULTI_THREADED=Y /QOpenSys/QIBM/ProdData/JavaVM/jdk80/64bit/bin/java -Dos400.stdio.convert=N -jar /QOpenSys/pkgs/lib/mapepire/mapepire-server.jar --traceOn
```
If you run this command as an *ALLOBJ user, it should generate a file that starts with VSCode and ends with an .html extension in `/QOpenSys/pkgs/lib/mapepire/`. Otherwise, it will be an HTML file in `/tmp/`.

The following error was found in the .html file:
```
java.net.UnknownHostException: <redacted.domain.com>: <redacted.domain.com>: Hostname and service name not provided or found
	at java.net.InetAddress.getLocalHost(InetAddress.java:1704)
	at com.github.ibm.mapepire.certstuff.SelfSignedCertGenerator.generate(SelfSignedCertGenerator.java:24)
	at com.github.ibm.mapepire.certstuff.ServerCertGetter.get(ServerCertGetter.java:102)
	at com.github.ibm.mapepire.MapepireServer.main(MapepireServer.java:74)
Caused by: java.net.UnknownHostException: <redacted.domain.com>: Hostname and service name not provided or found
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:1048)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1481)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1699)
	... 3 more
```

The server couldn't resolve its own hostname. As this is a brand new LPAR for testing, no DNS records had been set up on the lookup servers. As soon as I created a DNS record for this server's hostname, the service was able to start up.

I recommend full DNS setup be listed as a requirement in the Mapepire setup documentation, i.e. fully resolvable hostname.
