### ISSUE TITLE
java.security.cert.CertificateException: No name matching host found

### ISSUE THREAD

**Issue by sgonchigar** [Mapepire-IBMi/mapepire-server#74]
Getting the below error when running the sample application for a remote IBMi host.

javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No name matching host found
	at com.ibm.jsse2.g.a(g.java:41)
	at com.ibm.jsse2.bb.a(bb.java:82)
	at com.ibm.jsse2.bb.a(bb.java:186)
	at com.ibm.jsse2.bb.a(bb.java:5)
	at com.ibm.jsse2.z$e.a(z$e.java:18)
	at com.ibm.jsse2.z$e.a(z$e.java:103)
	at com.ibm.jsse2.z$e.a(z$e.java:43)
	at com.ibm.jsse2.p.a(p.java:67)
	at com.ibm.jsse2.aa.a(aa.java:29)
	at com.ibm.jsse2.aa.a(aa.java:181)
	at com.ibm.jsse2.bb.a(bb.java:189)
	at com.ibm.jsse2.a0.a(a0.java:10)
	at com.ibm.jsse2.bj.b(bj.java:411)
	at com.ibm.jsse2.bj.f(bj.java:202)
	at com.ibm.jsse2.bj.a(bj.java:354)
	at com.ibm.jsse2.bj.f(bj.java:73)
	at com.ibm.jsse2.bj.access$200(bj.java:209)
	at com.ibm.jsse2.bj$b.read(bj$b.java:48)
	at java.io.InputStream.read(InputStream.java:113)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:543)
	at java.lang.Thread.run(Thread.java:825)
Caused by: java.security.cert.CertificateException: No name matching host found
	at com.ibm.jsse2.util.c.b(c.java:18)
	at com.ibm.jsse2.util.c.a(c.java:99)
	at com.ibm.jsse2.br.a(br.java:36)
	at com.ibm.jsse2.br.a(br.java:70)
	at com.ibm.jsse2.bp.a(bp.java:10)
	at com.ibm.jsse2.bp.checkServerTrusted(bp.java:79)
	at com.ibm.jsse2.z$e.a(z$e.java:82)
	... 16 more
Exception in thread "main" java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No name matching host found
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:368)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1919)
	at mapepire1.Mapepire1.runSqlDemo(Mapepire1.java:86)
	at mapepire1.Mapepire1.main(Mapepire1.java:35)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No name matching host found
	at com.ibm.jsse2.g.a(g.java:41)
	at com.ibm.jsse2.bb.a(bb.java:82)
	at com.ibm.jsse2.bb.a(bb.java:186)
	at com.ibm.jsse2.bb.a(bb.java:5)
	at com.ibm.jsse2.z$e.a(z$e.java:18)
	at com.ibm.jsse2.z$e.a(z$e.java:103)
	at com.ibm.jsse2.z$e.a(z$e.java:43)
	at com.ibm.jsse2.p.a(p.java:67)
	at com.ibm.jsse2.aa.a(aa.java:29)
	at com.ibm.jsse2.aa.a(aa.java:181)
	at com.ibm.jsse2.bb.a(bb.java:189)
	at com.ibm.jsse2.a0.a(a0.java:10)
	at com.ibm.jsse2.bj.b(bj.java:411)
	at com.ibm.jsse2.bj.f(bj.java:202)
	at com.ibm.jsse2.bj.a(bj.java:354)
	at com.ibm.jsse2.bj.f(bj.java:73)
	at com.ibm.jsse2.bj.access$200(bj.java:209)
	at com.ibm.jsse2.bj$b.read(bj$b.java:48)
	at java.io.InputStream.read(InputStream.java:113)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:543)
	at java.lang.Thread.run(Thread.java:825)
Caused by: java.security.cert.CertificateException: No name matching host found
	at com.ibm.jsse2.util.c.b(c.java:18)
	at com.ibm.jsse2.util.c.a(c.java:99)
	at com.ibm.jsse2.br.a(br.java:36)
	at com.ibm.jsse2.br.a(br.java:70)
	at com.ibm.jsse2.bp.a(bp.java:10)
	at com.ibm.jsse2.bp.checkServerTrusted(bp.java:79)
	at com.ibm.jsse2.z$e.a(z$e.java:82)
	... 16 more

**Comment by bashdi** [comment]
The created self-signed certificate has the hostname set as CN. If your connection address and the hostname arent matching, you get this SSLHandshakeException.

Example:
Hostname is `test400`
`192.168.0.42` as connection address throws exception.
`test400` as connection address works fine

You can find the set hostname in the mapepire-log after startup:
`Starting daemon...2024-09-23 07:32:46.779:INFO::main: Logging initialized @414ms to org.eclipse.jetty.util.log.StdErrLog
Starting server for 192.168.0.42 on port 8076
2024-09-23 07:32:47.135:INFO:oejs.Server:main: jetty-9.4.54.v20240208; built: 2024-02-08T19:42:39.027Z; git: cef3fbd6d736a21e7d541a5db490381d95a2047d; jvm 17.0.12+7-LTS
2024-09-23 07:32:47.172:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2024-09-23 07:32:47.172:INFO:oejs.session:main: No SessionScavenger set, using defaults
2024-09-23 07:32:47.176:INFO:oejs.session:main: node0 Scavenging every 600000ms
2024-09-23 07:32:47.218:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@2cbb3d47{/,null,AVAILABLE}
2024-09-23 07:32:47.228:INFO:oejus.SslContextFactory:main: x509=X509@2a32de6c(mapepire,h=[test400],a=[],w=[]) for Server@7692d9cc[provider=null,keyStore=null,trustStore=null]
2024-09-23 07:32:47.518:INFO:oejs.AbstractConnector:main: Started ServerConnector@2a17b7b6{SSL, (ssl, http/1.1)}{0.0.0.0:8076}
2024-09-23 07:32:47.520:INFO:oejs.Server:main: Started @1156ms`

In this line(test400):
`2024-09-23 07:32:47.228:INFO:oejus.SslContextFactory:main: x509=X509@2a32de6c(mapepire,h=[test400],a=[],w=[]) for Server@7692d9cc[provider=null,keyStore=null,trustStore=null]`

If you`r just testing the mapepire-server you could set the env-Variable `MP_UNSECURE=true` before starting it to create a **unsecure** connection, which would avoid this exception. Keep in mind your credentials will be send unencrypted.

**Comment by sgonchigar** [comment]
On the IBMi, it is local and shows as test400.  I was running the sample java pgm on the pc (client) and I had the host name as test400.domain.com. On the client, when specified hostname as test400, it can't reach the server and when used test400.domain.com. It can reach the server but fails the certificate authentication. 

When used MP_UNSECURE=true, connection is getting refused.
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:96)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:380)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:236)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:218)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.net.Socket.connect(Socket.java:682)
	at com.ibm.jsse2.bj.connect(bj.java:220)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:491)
	at java.lang.Thread.run(Thread.java:825)
Exception in thread "main" java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: connect
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:368)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1919)
	at mapepire1.Mapepire1.runSqlDemo(Mapepire1.java:97)
	at mapepire1.Mapepire1.main(Mapepire1.java:46)

**Comment by bashdi** [comment]
hm, currently i not able to find the same sample java application but i think you need to change this line:

`return new DaemonServer(host, port, user, password, true, "");`

to

`return new DaemonServer(host, port, user, password,  false, "");`

To allow no encryption

**Comment by sgonchigar** [comment]
I tried that and still got "Unsupported or unrecognized SSL message".

**Comment by bashdi** [comment]
Right now im just guessing, i didnt try it.
I think currently the java sdk isnt supporting an unencrypted connection, because in the uri it is explicitly telling to use wss(websocket secure) and not ws(websocket).

> URI uri = new URI("wss://" + db2Server.getHost() + ":" + db2Server.getPort() + "/db/");

**Comment by sgonchigar** [comment]
where would I be making that change?

**Comment by SanjulaGanepola** [comment]
Hello @sgonchigar. Thank you for posting this issue. Seems like the problem is that certificate common name is set to `test400` instead of the fully qualified name. Thus, in the client when you use the host name `test400.domain.com` you will get `CertificateException: No name matching host found`. However, in the client if you then try to use the host name `test400` that will not allow you to connect to the server as it probably cannot resolve it.

Can you use the `CFGTCP` command and use option 12 and share the host and domain name configuration for your IBM i to see what is wrong:

![image](https://github.com/user-attachments/assets/29680ffd-1583-47f5-a23f-8f7c97f7a5c2)

**Comment by sgonchigar** [comment]
![image](https://github.com/user-attachments/assets/81f0ae15-b61f-4839-b9b3-68b8dd68e770)
hostname = test400
Domain name =  domain.com

**Comment by william-xiang** [comment]
Hi @sgonchigar, we tried to reproduce this issue on our end but we had no luck. 
Could you run this Java code snippet and see what's the output on your IBM i?

```
import java.net.InetAddress;
import java.net.UnknownHostException;

public class Test {
	public static void main(String[] args) throws UnknownHostException {
		InetAddress localHost = InetAddress.getLocalHost();
		System.out.println(localHost.getHostName());
		System.out.println(localHost.getHostAddress());
		System.out.println(localHost.getCanonicalHostName());
	}
}
```

Please also share the result of `hostname` command in either bash or qsh.

**Comment by sgonchigar** [comment]
java Test result. 
TEST400      
123.123.123.123
TEST400

**Comment by SanjulaGanepola** [comment]
> hm, currently i not able to find the same sample java application but i think you need to change this line:

@bashdi FYI, the Java sample projects can be found here: https://github.com/Mapepire-IBMi/samples/tree/main/java

> `return new DaemonServer(host, port, user, password,  false, "");`

This `ignoreUnauthorized` field on the `DaemonServer` object at the moment does not do anything. Once handling of certificates is implemented, it will be used to control whether to ignore unauthorized certificates.

> I think currently the java sdk isnt supporting an unencrypted connection, because in the uri it is explicitly telling to use wss(websocket secure) and not ws(websocket)

Yes, that is correct. The client SDKs do not support unencrypted connections.

**Comment by SanjulaGanepola** [comment]
> java Test result.
> TEST400
> 123.123.123.123
> TEST400

@sgonchigar Can you also share the result of running the `hostname` command in bash or qsh?

**Comment by sgonchigar** [comment]
hostname command on qsh shows  TEST400.domain.com
![image](https://github.com/user-attachments/assets/bc45d768-96e7-4d83-a3af-877cfb2aff17)

**Comment by william-xiang** [comment]
> java Test result. 
> TEST400 
> 123.123.123.123 
> TEST400
@sgonchigar It's a bit interesting now. On our machines, the first value of the returned result is always the FQDN specified using CFGTCP command. Is the IP address in your result the same as the one resolved for TEST400.example.com?

Could you also share these two configurations on your machine?
1. TCP/IP interfaces
CFGTCP -> Option 1
2. Host table entries
CFGTCP -> Option 10

**Comment by sgonchigar** [comment]
Hi William, here is the requested information.
![image](https://github.com/user-attachments/assets/2fcc237c-a8ec-4cc0-a5d6-3a8ed04053e7)

![image](https://github.com/user-attachments/assets/33081585-42c1-4717-bcdc-30717e3f6727)

![image](https://github.com/user-attachments/assets/cffcbd43-91ce-4602-8331-0d11d75ad21b)

**Comment by eric-simpson** [comment]
@sgonchigar can this be closed?

**Comment by sgonchigar** [comment]
Yes. Thank you for the follow up.
