### ISSUE TITLE
Connect method throwing null pointer

### ISSUE THREAD

**Issue by worksofliam** [Mapepire-IBMi/mapepire-server#84]
Reported by a user. From the VS Code logs.

```
QIBM_JAVA_STDIO_CONVERT=N QIBM_PASE_DESCRIPTOR_STDIO=B QIBM_USE_DESCRIPTOR_STDIO=Y QIBM_MULTI_THREADED=Y exec /QOpenSys/QIBM/ProdData/JavaVM/jdk80/64bit/bin/java -Dos400.stdio.convert=N -jar $HOME/.vscode/mapepire-server-2.1.4.jar --single
{"id":"id20","type":"connect","technique":"tcp","application":"vscode-db2i 1.6.3","props":"libraries=QGPL,QGPL,QTEMP;naming=system;full open=false;transaction isolation=none;query optimize goal=1;block size=512"}
{"id":"id20","error":"java.lang.NullPointerException","success":false,"sql_state":null,"sql_rc":0}
Exited with code 12.
```

Both from the terminal/bash and through VS Code.

I am not able to recreate it.

**Comment by worksofliam** [comment]
Steps to recreated:

```
QIBM_JAVA_STDIO_CONVERT=N QIBM_PASE_DESCRIPTOR_STDIO=B QIBM_USE_DESCRIPTOR_STDIO=Y QIBM_MULTI_THREADED=Y exec /QOpenSys/QIBM/ProdData/JavaVM/jdk80/64bit/bin/java -Dos400.stdio.convert=N -jar $HOME/.vscode/mapepire-server-2.1.4.jar --single
```

```
{"id":"id4","type":"setconfig","tracedest":"FILE","tracelevel":"ERRORS"}
```

```
{"id":"id20","type":"connect","technique":"tcp","application":"vscode-db2i 1.6.3","props":"libraries=QGPL,QGPL,QTEMP;naming=system;full open=false;transaction isolation=none;query optimize goal=1;block size=512"}
```

**Comment by worksofliam** [comment]
```
[INFO]: 2024-11-08.16.22.57.519
Tracing enabled to file '/home/JUANMA/.vscode/vsc-2024-11-08.16.22.41.245-78623129846867.html'
[ERR]: 2024-11-08.16.22.57.519
java.sql.SQLException: java.lang.NullPointerException
	at com.github.ibm.mapepire.SystemConnection.reconnect(SystemConnection.java:193)
	at com.github.ibm.mapepire.requests.Reconnect.go(Reconnect.java:38)
	at com.github.ibm.mapepire.ClientRequest.run(ClientRequest.java:85)
	at com.github.ibm.mapepire.DataStreamProcessor.dispatch(DataStreamProcessor.java:64)
	at com.github.ibm.mapepire.DataStreamProcessor.dispatch(DataStreamProcessor.java:58)
	at com.github.ibm.mapepire.DataStreamProcessor.run(DataStreamProcessor.java:176)
	at com.github.ibm.mapepire.DataStreamProcessor.run(DataStreamProcessor.java:84)
	at com.github.ibm.mapepire.MapepireServer.main(MapepireServer.java:52)
Caused by: java.lang.NullPointerException
	at com.ibm.as400.access.AS400StrSvrDS.(AS400StrSvrDS.java:26)
	at com.ibm.as400.access.AS400ImplRemote.getConnection(AS400ImplRemote.java:1611)
	at com.ibm.as400.access.AS400ImplRemote.connect(AS400ImplRemote.java:608)
	at com.ibm.as400.access.AS400.connectService(AS400.java:1612)
	at com.ibm.as400.access.AS400.connectService(AS400.java:1567)
	at com.ibm.as400.access.AS400JDBCConnectionImpl.setProperties(AS400JDBCConnectionImpl.java:3519)
	at com.ibm.as400.access.AS400JDBCDriver.prepareConnection(AS400JDBCDriver.java:1473)
	at com.ibm.as400.access.AS400JDBCDriver.initializeConnection(AS400JDBCDriver.java:1307)
	at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:456)
	at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:265)
	at java.sql.DriverManager.getConnection(DriverManager.java:675)
	at java.sql.DriverManager.getConnection(DriverManager.java:281)
	at com.github.ibm.mapepire.SystemConnection.reconnect(SystemConnection.java:189)
	... 7 more

[ERR]: 2024-11-08.16.23.23.437
java.io.IOException: System call error number -2.

	at java.io.FileInputStream.read(FileInputStream.java:272)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:295)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:356)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:323)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:365)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:211)
	at java.io.InputStreamReader.read(InputStreamReader.java:205)
	at java.io.BufferedReader.fill(BufferedReader.java:172)
	at java.io.BufferedReader.readLine(BufferedReader.java:335)
	at java.io.BufferedReader.readLine(BufferedReader.java:400)
	at com.github.ibm.mapepire.DataStreamProcessor.run(DataStreamProcessor.java:75)
	at com.github.ibm.mapepire.MapepireServer.main(MapepireServer.java:52)
```

**Comment by eric-simpson** [comment]
@VinodTech92 can you check if this is still reproducable?
